### ISSUE TITLE
1st MVP

### ISSUE THREAD

**Issue by nmhalloran** [nmhalloran/modern-hospitium#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by AAlfarho** [comment]
Great progress, this MVP is almost complete, there are a couple of details, some of them cosmetic, that we need to address before moving on to the next MVP.

- [x] I see that your `placeholder= Username`, has a whitespace, having that makes the actual input look weird when typing in it. Let's remove that whitespace and set `padding-left: 10px;` or some other padding you like, that way it will look more like this with the cursor 
![screen shot 2018-06-07 at 4 22 45 pm](https://user-images.githubusercontent.com/1103663/41131161-107132ce-6a6f-11e8-8ddd-f16f08e5e6e4.png)
instead of
![screen shot 2018-06-07 at 4 23 29 pm](https://user-images.githubusercontent.com/1103663/41131172-23b24904-6a6f-11e8-92a5-90152c503bfa.png)
- [x] Lets add to all links/navlinks/clickable elements the rule for cursors, `cursor: pointer`.
- [x] The placeholder for the password is currently being set to 'Email', is this expected?.
- [x] If the above is not expected then, will users log with username / password? If yes, then we might need to rephrase a couple of elements. 
![screen shot 2018-06-07 at 4 26 41 pm](https://user-images.githubusercontent.com/1103663/41131523-073fe298-6a71-11e8-8c66-bd8beba545c1.png)

- [x] We should be able to close modals also by hitting `esc`.
- [x]  Going to a random route /#/randomroute should redirect to either /, /login, or /signup. This means we need a default route in our switch.
- [x] Your spash page contains a `Why Join?` section, we need to place something in this section.
- [x] I noticed you are not using a reset css file, we need to add this to so that our app has the same look & feel crossbrowser.  ![screen shot 2018-06-07 at 4 31 47 pm](https://user-images.githubusercontent.com/1103663/41131411-83e0b580-6a70-11e8-9a0f-4df7bee6e932.png)

Feel free to check the items in this list and assign this issue back to me once the mentioned points are addressed.
